### PR TITLE
Update for Sphinx >= 4.0

### PR DESCRIPTION
**Pull request by JustinGoheen**
resolves issue#92

### CODE REVIEW

**Comment by JustinGoheen** [comment]
Steps taken:

- Removed Black version from setup.py
- updated Python versions in setup.py to include Python >=3.9
- in get_signatures.py
  - changed `from sphinx.util.inspect import Signature` to `from sphinx.util.inspect import signature`
  - added `from sphinx.util.inspect import stringify_signature`
  - changed get_signature_end as shown below

```python
def get_signature_end(function):
    sig = signature(function)
    signature_end = stringify_signature(sig, show_annotation=False)
    if utils.ismethod(function):
        signature_end = signature_end.replace("(self, ", "(")
        signature_end = signature_end.replace("(self)", "()")
    return signature_end
```

- ran tests (with pytest, not Docker image); results shown below
Screen Shot 2022-04-19 at 10 19 49 AM

**Comment by gabrieldemarmiesse** [comment]
Sadly I don't have many right anymore in this repository. I can't approve the workflow to run. Maybe this repo could be transferred to my github username, so that I can continue to maintain it? @qlzh727 what  do you think? Can we transfer this repo under @gabrieldemarmiesse ? Or do you want to keep it there and re-add me as maintainer?

**Comment by JustinGoheen** [comment]
The commit at [bab0aa5](https://github.com/keras-team/keras-autodoc/pull/93/commits/bab0aa5bc46897d7a1f4bfbf2f5e71c3ec8f5995) resolved the remaining failed test.
Screen Shot 2022-04-19 at 1 41 03 PM

**Comment by JustinGoheen** [comment]
I've forked and updated the project with a new package name for folks to use until this is resolved.

https://github.com/JustinGoheenAI/easy-sphinx

**Comment by JustinGoheen** [comment]
I've moved my fork to a new repo and added support for [material-for-mkdocs](https://squidfunk.github.io/mkdocs-material/).

https://github.com/JustinGoheen/material-sphinx

**Pull request closed without merging**
